### ISSUE TITLE
Request: Remove the limit of tag name?

### ISSUE THREAD

**Issue by frostming** [antfu/changelogithub#10]
Currently, the generator checks if a ref is a tag by looking at the first letter, if it isn't `v`, the process will abort. https://github.com/antfu/changelogithub/blob/6b764050d6c5c5fdc64784d4f0afcfe3a7d41270/src/cli.ts#L49-L53
It seems not ideal and will prevent it from being adopted by existing workflows.

Maybe we can remove this limit by changing to a more robust checking method, such as the full name of the ref (`refs/tag/${tagname}`).

**Comment by antfu** [comment]
Sure. Or maybe we could check if the tag exists on GitHub to be more safe?

**Comment by frostming** [comment]
Yeah, there are more than one approaches, list as follows:

- `git describe --exact-match HEAD` will return error if HEAD is not a tag
-  `git describe --dirty --tags` will show a distance>0 if HEAD is not a tag, or clean tag otherwise
-  Check the tag name exists under `.git/refs/tags/`

**Comment by antfu** [comment]
We want to push to GitHub's release for the target tag. Where there might be some cases the local tags are not in sync with the remote ones. We can use https://docs.github.com/en/rest/git/tags#get-a-tag to check if the tag exists on the remote. PR welcome
