### ISSUE TITLE
Feature request: Remove keywords used for references in commit message

### ISSUE THREAD

**Issue by Zolyn** [antfu/changelogithub#23]
When we use keywords (e.g. `closes`, `fixes`, `resolves`) to link an issue or a pull request in commit message, the changelog will look like this:

- Duplicate logs, fixes - in ...(references)

**Comment by antfu** [comment]
Can you share more details?

**Comment by Zolyn** [comment]
Take this commit message as an example

![2022-07-04_03-28](https://user-images.githubusercontent.com/35414841/177054785-c0cd0273-cd6b-45aa-a556-823637357fc7.png)

If we generate a change log for it, it will look like this

![2022-07-04_03-36](https://user-images.githubusercontent.com/35414841/177054809-dafdc761-c3de-4254-8675-dfc0aabe00b7.png)

(The content in the image below is from [here](https://github.com/Zolyn/changelogithub/blob/main/CHANGELOG.md#066-2022-06-18))

![2022-07-04_03-42](https://user-images.githubusercontent.com/35414841/177054934-7d325dcc-309a-4da3-82b5-1d2f957266c0.png)

IMO, it looks a little strange. (Of course, it could be that my English comprehension is not good enough 🤣 )
