### ISSUE TITLE
npx changelogithub not working for repo name with dot

### ISSUE THREAD

**Issue by sozonome** [antfu/changelogithub#3]
I have a repo named `sznm.dev` and `spoker`
It works on `spoker` but not on `sznm.dev`

Reproduction link:
https://github.com/sozonome/sznm.dev/runs/6859948295?check_suite_focus=true#step:4:9
![image](https://user-images.githubusercontent.com/17046154/173340571-dbc33c00-d9cc-4aae-b319-3ce92947b511.png)

I think the issue is within the regex being used in [`git.ts`](https://github.com/antfu/changelogithub/blob/main/src/git.ts#L6)
https://regex101.com/r/8G1j7G/1

**Comment by luke358** [comment]
I think the easiest way to use `/github\.com[\/:]([\w\d_-]+)\/(.+)(\.git)?$/`

**Comment by luke358** [comment]
or `github\.com[\/:]([\w\d_-]+)\/([\w\d_-]+.?[\w\d_-]+)(\.git)?$`

**Comment by luke358** [comment]
or `github\.com[\/:]([\w\d_-]+)\/([\w\d_-]+.?[\w\d_-]+)(\.git)?$`

**Comment by luke358** [comment]
`github\.com[\/:]([\w\d_-]+)\/([\w\d_-]+[\.\w\d_-]+)(\.git)?$`

**Comment by luke358** [comment]
`/github\.com[\/:]([\w\d_-]+)\/((?<=\/)[^\/]+)(\.git)/i`

**Comment by luke358** [comment]
`/github\.com[\/:]([\w\d_-]+)\/((?<=\/)[^\/]+)(\.git)$/i`

**Comment by luke358** [comment]
use `/github\.com[\/:]([\w\d._-]+)\/([\w\d._-]+)(\.git)?$/i`.
 (\.git) will not be able to be captured @ @antfu 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/48149577/173389315-053cfe88-6afd-4a5b-849f-248590d06e9f.png">

**Comment by sozonome** [comment]
Now it's successful. Thank you @antfu ! 🙇
