### ISSUE TITLE
Generate/Upudate CHANGELOG.md file

### ISSUE THREAD

**Issue by jd-solanki** [antfu/changelogithub#31]
### Clear and concise description of the problem

This package is really useful and I am using it for my [OSS project](https://github.com/jd-solanki/anu). However, my company maintains `CHANGELOG.md` file and changelogithub doesn't generate/update changelog.md file.

### Suggested solution

Maybe passing file option to update the changelog file

### Alternative

N/A

### Additional context

Thanks so much for your tools ❤️ 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's something that `changelogithub` is not designed for. I don't mind exposing some API to make it easier but it probably won't be a builtin feature. You can probably try using `changelogen` directly.

**Comment by jd-solanki** [comment]
Thanks for your response.

**Comment by tjx666** [comment]
I would like to genegrate release note on github using this cli. But the changelog local is also very useful sometimes. This cli powered by changelogen, but some default config is not the same. I would like to using this cli to generate the local changelog and github release with the same content.

@antfu
