### ISSUE TITLE
Why always No significant changes?

### ISSUE THREAD

**Issue by tjx666** [antfu/changelogithub#35]
### Describe the bug

I'm first to use this tool to auto release on github.

But every time release content is:

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/41773861/219885127-bcaa6060-f262-477b-8a53-9e930b3356e0.png">

I see https://github.com/antfu/unplugin-vue-components changelog is:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/219885311-e2323a54-b7ca-465f-b4f3-b7133428e619.png">

### Reproduction

https://github.com/tjx666/unplugin-externalize-deps/releases

### System Info

```Shell
Not need
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It only generate for fix/feat/perf by default: https://github.com/antfu/changelogithub/blob/f6995c9cb4dda18a0fa21efe908a0ee6a1fc26b9/src/config.ts#L11-L13

**Comment by so1ve** [comment]
@antfu Hi, sorry for commenting in a closed issue. It seems this is a bug.
You committed https://github.com/antfu/changelogithub/commit/92c3817e03e309401ae910216ab9a77dd2e48162, which begins with `feat`, however the [changelog](https://github.com/antfu/changelogithub/releases/tag/v0.12.9) does not contain this change.
